# Generated by Django 3.1.3 on 2020-11-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201127_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=28, verbose_name='counter-agent'),
        ),
    ]
