# Generated by Django 2.1.15 on 2020-11-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201127_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('pk',)},
        ),
    ]
