# Generated by Django 2.1.15 on 2020-11-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201127_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'counter-agent'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=28, verbose_name='name'),
        ),
    ]
